### ISSUE TITLE
Requesting list of Dependency Libraries

### ISSUE THREAD

**Issue by biswajitkgp** [linhkienthuduc21/esp32_pppos_arrduino#1]
First of all thank you for creating a library supporting ESP32 for the A7670C Module. 

I was trying to burn the simple_pppos_with_mqtt.ino to my ESP32 but I am receiving many compilation errors may be due to dependencies. Can you give me a list of all the libraries I need to install so that I can burn this code?

**Comment by nguyendu382** [comment]
First you need to install ardunio IDE version less than 2.0.0 (i.e 1.8.16).
Then add libraries: PPPOSClient by Igor Levkov and PubSubClient by Nick O'Leary.

**Comment by TDLOGY** [comment]
Hi @biswajitkgp please install ESP32 version 1.0.6. Because of espressif have seperate ppp from esp-idf to module from esp-idf 5.0
